# Generated by Django 3.0.5 on 2020-04-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', null=True, upload_to='pic_folder/'),
        ),
    ]
