# Generated by Django 3.0.5 on 2020-04-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Uploaded image'),
        ),
    ]
