# Generated by Django 3.0.5 on 2020-04-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.TextField()),
                ('total_price', models.IntegerField()),
                ('observations', models.IntegerField()),
                ('status_place', models.BooleanField()),
                ('state', models.BooleanField()),
            ],
        ),
    ]
