# Generated by Django 3.0.5 on 2020-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='observations',
            field=models.TextField(),
        ),
    ]
